### ISSUE TITLE
Tutorial : Create M2C Stack

### ISSUE THREAD

**Issue by gmarchand** [aws-solutions/media2cloud-on-aws#23]
**Describe the bug**

**To Reproduce**
[Steps to reproduce the behavior.](https://github.com/aws-solutions/media2cloud-on-aws/blob/main/deployment/tutorials/1-creating-media2cloud-stack.md)

```
aws cloudformation create-stack \
  --stack-name \
    m2c-demo \
  --template-url \
    https://solutions-reference.s3.amazonaws.com/media2cloud/latest/media2cloud.template \
  --parameters \
    "ParameterKey=Email,ParameterValue=\"yourname@company.com\"" \
    "ParameterKey=PriceClass,ParameterValue=\"Use Only U.S., Canada and Europe (PriceClass_100)\"" \
    "ParameterKey=OpenSearchCluster,ParameterValue=\"Development and Testing (t3.medium=0,m5.large=1,gp2=10,az=1)\"" \
    "ParameterKey=DefaultAIOptions,ParameterValue=\"All (celeb,face,facematch,label,moderation,person,text,segment,transcribe,keyphrase,entity,sentiment,textract)\"" \
    "ParameterKey=StartOnObjectCreation,ParameterValue=\"NO\"" \
  --capabilities \
    "CAPABILITY_IAM" \
    "CAPABILITY_NAMED_IAM" \
    "CAPABILITY_AUTO_EXPAND"

An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [KnowledgeGraphApiKey, KnowledgeGraphEndpoint, BlipImageArn] must have values
```

**Expected behavior**
The stack should deploy

**Please complete the following information about the solution:**
- [ ] Version: 3.1.0
- [ ] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes
- [ ] Were there any errors in the CloudWatch Logs? No

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by karolmalinski** [comment]
Hi gmarchand!
I have encountered the same issue. You can workaround this by providing `Default` values for these parameters, like this:
```
    # Neptune Knowledge Graph endpoint
    KnowledgeGraphEndpoint:
        Type: String
        Description: specify the API endpoint of the Knowledge Graph database. Leave it blank to disable the feature.
        Default: ""
    KnowledgeGraphApiKey:
        Type: String
        Description: specify the API Key of the Knowledge Graph API endpoint. Leave it blank to disable the feature.
        Default: ""
    # BLIP model (auto caption for image)
    BlipImageArn:
        Type: String
        Description: specify the ECR image Arn of the Auto Captioning feature (BLIP model), ie., {{account}}.dkr.ecr.{{region}}.amazonaws.com/{{repo}}:{{tag}}. Leave it blank to disable the feature.
        Default: ""
```
